# This is the configuration used to check the rubocop source code.

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/EndOfLine:
  EnforcedStyle: lf
