version: 2
jobs:
  build:
    working_directory: ~/attr_hasher

    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - attr_hasher-{{ checksum "Gemfile.lock" }}
            # - attr_hasher-

      - run:
          name: Install bundler
          command: gem install bundler

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      # Store bundle cache
      - save_cache:
          key: attr_hasher-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: RSpec
          command: rspec

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results