---
version: 2
jobs:
  build:
    parameters:
      sonar-login:
        description:
        type: env_var_name
        default: SONAR_LOGIN

    working_directory: ~/attr_hasher

    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - attr_hasher-{{ checksum "Gemfile.lock" }}
            # - attr_hasher-

      - run:
          name: Install bundler
          command: gem install bundler

      - run:
        name: Install sonar-scanner
        command: >
          curl -s -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip -o sonarscanner.zip &&
          unzip -qq sonarscanner.zip &&
          rm -rf sonarscanner.zip &&
          mv sonar-scanner-3.3.0.1492-linux sonar-scanner

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      # Store bundle cache
      - save_cache:
          key: attr_hasher-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: RSpec
          command: bundle exec rspec

      - run:
          name: SonarQube scan
          command: sonar-scanner -Dsonar.projectKey=sapientpants_attr_hasher -Dsonar.organization=sapientpants-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=<<parameters.sonar-login>>

      # Save artifacts
      # - store_test_results:
      #     path: /tmp/test-results